// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7aCbt--yYLbXPiR8jIm4WDjSR3eJyqxM',
    appId: '1:1034985636504:web:5f6b0e81856ce1baa346ed',
    messagingSenderId: '1034985636504',
    projectId: 'scissor-s',
    authDomain: 'scissor-s.firebaseapp.com',
    databaseURL: 'https://scissor-s-default-rtdb.firebaseio.com',
    storageBucket: 'scissor-s.appspot.com',
    measurementId: 'G-B4XQG5WL9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh6LdGqmTlSKQH5lnp11Zkx3hHzevOLYY',
    appId: '1:1034985636504:android:ef549d8f3477e0c0a346ed',
    messagingSenderId: '1034985636504',
    projectId: 'scissor-s',
    databaseURL: 'https://scissor-s-default-rtdb.firebaseio.com',
    storageBucket: 'scissor-s.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqVlOz-d_g1867MlL5CyOwJqmOAEdrgzM',
    appId: '1:1034985636504:ios:c0f3e0978ce82760a346ed',
    messagingSenderId: '1034985636504',
    projectId: 'scissor-s',
    databaseURL: 'https://scissor-s-default-rtdb.firebaseio.com',
    storageBucket: 'scissor-s.appspot.com',
    iosClientId: '1034985636504-guptlqdfr5civ6rj280en16u6p1isnrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sissiors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqVlOz-d_g1867MlL5CyOwJqmOAEdrgzM',
    appId: '1:1034985636504:ios:09bd6e227f583310a346ed',
    messagingSenderId: '1034985636504',
    projectId: 'scissor-s',
    databaseURL: 'https://scissor-s-default-rtdb.firebaseio.com',
    storageBucket: 'scissor-s.appspot.com',
    iosClientId: '1034985636504-qco4e6esrqihkobre6j5vm3562s5gsdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sissiors.RunnerTests',
  );
}
